---
title: "R Markdown HTML output demo"
author: Andrew Caines | DTAL, UCAM | apc38
date: 19 January 2015
output:
  html_document:
    theme: journal
    highlight: espresso
---


## Inline R code

Beware of counting your chickens: `1 + 1` does not always equal `r 1 + 1`!


## R code chunks

#### echo=T, eval=F
```{r, eval=FALSE}
summary(cars)
```

#### echo=T, eval=T (default)
```{r}
str(cars)
head(cars)
summary(cars)
```

```{r}
plot(cars)
```

#### echo=F, eval=T
```{r, echo=FALSE}
ggplot(mtcars, aes(x = mpg, fill = factor(cyl))) + geom_dotplot(stackgroups = TRUE, binwidth = 1, method = "histodot")
```


## Embedding equations

You can embed LaTeX equations using '$'-signs: $E=mc^2$


## Render your document

- With 'knit' (Ctrl+Shift+K) in RStudio...
- Or `rmarkdown::render('filename.Rmd')` in R.


## Remote collaboration

- [Wieling e.g. Rmd](http://www.let.rug.nl/~wieling/statscourse/lecture1/lab/answers/lab-including-answers.Rmd)
- [Wieling e.g. HTML](http://www.let.rug.nl/~wieling/statscourse/lecture1/lab/answers/lab-including-answers.html)
